rules:
    default:
        protection:
            required_pull_request_reviews: null
            required_status_checks:
                contexts:
                - continuous-integration/travis-ci
        enabling_label: enable-mergify
        disabling_files:
        - .mergify.yml
        - .travis.yml
    branches:
        master: null
