# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-13 18:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0129_remove_osfuser_is_claimed'),
        ('osf', '0129_merge_20180910_1926'),
        ('osf', '0129_abstractnode_custom_citation'),
    ]

    operations = [
    ]
