# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-13 19:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0130_merge_20180913_1815'),
        ('osf', '0124_merge_20180815_1924'),
    ]

    operations = [
    ]
