# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-17 15:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0131_merge_20180913_1946'),
        ('osf', '0132_merge_20180914_2001'),
    ]

    operations = [
    ]
