# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-17 15:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0129_merge_20180831_1412'),
        ('osf', '0133_merge_20180917_1500'),
    ]

    operations = [
    ]
