# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-21 18:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0134_merge_20180917_1515'),
        ('osf', '0134_merge_20180921_1312'),
    ]

    operations = [
    ]
